export const REQUEST_JOURNEY = "REQUEST_JOURNEY";
export const RECEIVE_JOURNEY = "RECEIVE_JOURNEY";
export const FETCH_JOURNEY_ERROR = "FETCH_JOURNEY_ERROR";
export const RECEIVE_JOURNEY_ERROR = "RECEIVE_JOURNEY_ERROR";
export const TOGGLE_EDITING = "TOGGLE_EDITING";
export const NETWORK_CONNECTION_ERROR = "NETWORK_CONNECTION_ERROR";

